### PR TITLE
[WIP] [PORT] sale modules

### PR DESCRIPTION
**Pull request by iledarn**

### CODE REVIEW

**Comment by yelizariev** [comment]
Done?

**Comment by iledarn** [comment]
@yelizariev , website_sale_require_login hasn't ported yet

**Comment by yelizariev** [comment]
Fix saas_portal_portal

```

2016-11-02 05:47:43,762 14594 INFO 00941-357-b0d074--all---portal odoo.modules.loading: loading saas_portal_portal/views/templates.xml
2016-11-02 05:47:43,822 14594 ERROR 00941-357-b0d074--all---portal odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/mnt/odoo-extra/runbot/static/build/00941-357-b0d074/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/mnt/odoo-extra/runbot/static/build/00941-357-b0d074/odoo/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/mnt/odoo-extra/runbot/static/build/00941-357-b0d074/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/mnt/odoo-extra/runbot/static/build/00941-357-b0d074/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/mnt/odoo-extra/runbot/static/build/00941-357-b0d074/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/mnt/odoo-extra/runbot/static/build/00941-357-b0d074/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/mnt/odoo-extra/runbot/static/build/00941-357-b0d074/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/mnt/odoo-extra/runbot/static/build/00941-357-b0d074/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/mnt/odoo-extra/runbot/static/build/00941-357-b0d074/odoo/tools/convert.py", line 780, in _tag_template
    return self._tag_record(record, data_node)
  File "/mnt/odoo-extra/runbot/static/build/00941-357-b0d074/odoo/tools/convert.py", line 698, in _tag_record
    f_val = self.id_get(f_ref)
  File "/mnt/odoo-extra/runbot/static/build/00941-357-b0d074/odoo/tools/convert.py", line 785, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/mnt/odoo-extra/runbot/static/build/00941-357-b0d074/odoo/tools/convert.py", line 791, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/mnt/odoo-extra/runbot/static/build/00941-357-b0d074/odoo/addons/base/ir/ir_model.py", line 1027, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<string>", line 2, in xmlid_lookup
  File "/mnt/odoo-extra/runbot/static/build/00941-357-b0d074/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/00941-357-b0d074/odoo/addons/base/ir/ir_model.py", line 1016, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ParseError: "External ID not found in the system: website_portal.account" while parsing None:9, near
<data name="SaaS Custom Panel" inherit_id="website_portal.account">
    <xpath expr="//div[@id='o_my_sidebar']" position="inside">
      <t t-if="saas_portal_client">
        <div class="oe_structure">
          <h3 class="page-header">Domain <a href="/my/domain" class="btn btn-default btn-xs">Change</a></h3>

          <p><t t-esc="saas_portal_client.name"/></p>

        </div>
      </t>
    </xpath>
  </data>
```

**Comment by ilmir-k** [comment]
```
Failed to load registry
Traceback (most recent call last):
  File "/mnt/odoo-extra/runbot/static/build/00944-357-acd90e/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/mnt/odoo-extra/runbot/static/build/00944-357-acd90e/odoo/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/mnt/odoo-extra/runbot/static/build/00944-357-acd90e/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/mnt/odoo-extra/runbot/static/build/00944-357-acd90e/odoo/modules/loading.py", line 177, in load_module_graph
    env['ir.ui.view']._validate_module_views(module_name)
  File "/mnt/odoo-extra/runbot/static/build/00944-357-acd90e/odoo/addons/base/ir/ir_ui_view.py", line 1180, in _validate_module_views
    self.raise_view_error("Can't validate view:\n%s" % (e.message or repr(e)), vid)
  File "/mnt/odoo-extra/runbot/static/build/00944-357-acd90e/odoo/addons/base/ir/ir_ui_view.py", line 454, in raise_view_error
    raise ValueError(message)
ValueError: Can't validate view:
Element <xpath expr="//div[contains(@class,'o_my_documents')]"> cannot be located in parent view

Error context:
View `Account`
[view_id: 637, xml_id: saas_portal_portal.account, model: n/a, parent_id: 356]

Error context:
View `Account`
[view_id: 637, xml_id: saas_portal_portal.account, model: n/a, parent_id: 356]
```

**Comment by yelizariev** [comment]
```
  Element '<xpath expr="//div[contains(@class,'o_my_documents')]">' cannot be located in parent view
```

**Pull request merged**
