### PR TITLE
[WIP] 11.0 migrate python3

### PR DESCRIPTION
**Pull request by njeudy**
- Begin to port to V11 and Python 3
- Module can be installed now

TODO:

- Need to add res_config_setting to change domain with new V11 way
- Tests

### CODE REVIEW

**Comment by njeudy** [comment]
reference https://github.com/it-projects-llc/access-addons/pull/62

**Comment by njeudy** [comment]
reference https://github.com/it-projects-llc/misc-addons/pull/484

**Comment by njeudy** [comment]
reference https://github.com/it-projects-llc/website-addons/pull/222

**Comment by yelizariev** [comment]
@njeudy thank you for your work. We scheduled to work on migration at Thursday  26th Oct, so I will merge all PR at that day to continue from your point of progress.

**Pull request merged**
